### ISSUE TITLE
Error message for simplefog using the Forge...

### ISSUE THREAD

**Issue by WildBillLives** [VanceCole/simplefog#7] opened 2020-09-25 16:16 UTC
I use The Forge to host my worlds/games, and I always get the following error message in the console when I start up any game with simplefog is enabled (im using Foundry v0.66 and Simplefog v 0.1.9):

TypeError: this.migration1 is not a function
    at Migrations.check (Migrations.js:12)
    at simplefog.js:32
    at Function._call (foundry.js:2239)
    at Function.callAll (foundry.js:2199)
    at Game.setupGame (foundry.js:5838)
    at async Game._initializeGameView (foundry.js:6469)
    at async Game.initialize (foundry.js:5754)

This error message will occur either with no other modules enabled or with my normal small set of modules enabled, so it does *not* appear to be caused by a conflict with another module. I do not note any specific issues this error causes, but i thought it might be good to post it in case it is an issue that needs to be addressed.

**Comment by VanceCole** [comment] 2020-09-26 04:09
Hello,

Thank you for the report. I see what the problem is and it will be fixed in the next version of Simplefog, I'll try to get a release out this weekend.

Thanks again for letting me know.

-Vance

**Comment by VanceCole** [comment] 2020-09-27 04:28
Should be fixed in release 0.1.10

**Closed by VanceCole** 2020-09-27 04:28 UTC
